#! /bin/sh
### BEGIN INIT INFO
# Provides:          ooo-xvfb
# Required-Start:    $network $xvfb
# Required-Stop:     $network 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop ooo-xvfb
# Description:       OpenOffice Headless Mode Server
# Author:            Normunds Vilcans, Alistek SIA
#                    
### END INIT INFO
 
#OOo_HOME=/usr/bin
#SOFFICE_PATH=$OOo_HOME/soffice

OOo_HOME=/usr/lib/libreoffice/program
SOFFICE_PATH=$OOo_HOME/soffice.bin
PIDFILE=/var/run/openoffice-server.pid
VDISPLAY='89' #should be the same as in xvfb init script
ADDRESS=localhost #can change to IP adress 

case "$1" in
start)
if [ -f $PIDFILE ]; then
echo "OpenOffice headless server has already started."
sleep 2
exit
fi
echo "Starting OpenOffice headless server"
$SOFFICE_PATH --nologo --nofirststartwizard --accept="socket,host=$ADDRESS,port=8100;urp" --display $VDISPLAY & > /dev/null 2>&1
touch $PIDFILE
;;
stop)
if [ -f $PIDFILE ]; then
echo "Stopping OpenOffice headless server."
killall -9 soffice && killall -9 soffice.bin
rm -f $PIDFILE
exit
fi
echo "Openoffice headless server is not running."
exit
;;
restart)
echo "Restarting " $0
killall -9 soffice && killall -9 soffice.bin
sleep 3
$0 stop
$0 start
;;
status)
CHECKPID=`pidof soffice.bin`
if [ "$CHECKPID" ]; then
	echo "OpenOffice Headless Server is Up (pid:$CHECKPID)"
else
	echo "OpenOffice Headless Server is not running"
fi
exit
;;
*)
echo "Usage: $0 {start|stop|status}"
exit 1
esac
exit 0 
